name: example
description: A simple widget helps with adding an effect to your swipe actions.
  You can use it by wrapping your widget with SwipeEffect and listen to the swipes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  swipe_effect:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true